channels:
- conda-forge
dependencies:
- python=3.10.16
- pip<=25.0
- pip:
  - mlflow==2.17.2
  - cloudpickle==3.1.1
  - numpy==1.26.0
  - pandas==2.2.3
  - timm==1.0.14
  - torch==2.6.0
name: mlflow-env
